baseURL = 'https://limemeeple.github.io/'
theme = 'hugo-book'
title = 'LimeMeeple'

locale = 'ko-kr'
defaultContentLanguage = 'ko'

[params]
googleAnalytics = "G-B577GZKLR0"

[params.BookMenu]
    profileImage = "/images/logo_img.png"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
<<<<<<< HEAD
      unsafe = true
=======
      unsafe = true
>>>>>>> 79f1acb72f98086da2ac4928c8171069d05c4059
